AWSTemplateFormatVersion: 2010-09-09
Description: Certification and DSN setup
Parameters:
  UniqueAppName:
    Type: String
  DomainName:
    Type: String
  LoadBalancerDNS:
    Type: String
    Default: pimcore-app-staging-alb-233318818.eu-central-1.elb.amazonaws.com #TODO
  LoadBalancerHostedZone:
    Type: String
    Default: 'Z215JYRZR1TBD5' #TODO get the value from the load balancer?
Resources:
  PimcoreInstanceCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${UniqueAppName}.${DomainName}'
      DomainValidationOptions:
        - DomainName: !Sub '${UniqueAppName}.${DomainName}'
          ValidationDomain: !Sub '${UniqueAppName}.${DomainName}'
      ValidationMethod: DNS
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Sub '${UniqueAppName}.${DomainName}'
      Type: A
      #TTL: '900'
      AliasTarget:
        DNSName: !Ref LoadBalancerDNS
        HostedZoneId: !Ref LoadBalancerHostedZone


Outputs:
  DomainName:
    Value: !Sub '${UniqueAppName}.${DomainName}'