AWSTemplateFormatVersion: 2010-09-09
Description: 'Create users and permissions to access and work with the Pimcore ECS stack.'
Parameters:
  Prefix:
    Type: String
    Description: 'Prefix for user permissions to avoid conflicts with other stacks. Must be numeric.'
Resources:

  # @see https://policysim.aws.amazon.com/ for simulating policies
  # Currently has permissions to execute copilot and perform cloudformation deployments
  SetupUser:
    Type: 'AWS::IAM::User'

  SetupUserGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: !Sub '${Prefix}-SetupUserGroup'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        #        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSCloudMapFullAccess # Route 53 and service discovery?
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
      Policies:
        # Restrict user to only access S3 bucket in current stack
        - PolicyName: !Sub "${Prefix}-setupUserS3Access"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectACL
                  - s3:PutObjectTagging
                  - s3:DeleteObject
                  - s3:RestoreObject
                Resource: !Sub 'arn:aws:s3:::${Prefix}/*'
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource: !Sub 'arn:aws:s3:::${Prefix}'

        - PolicyName: !Sub "${Prefix}-setupUserEc2Access"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeSubnets
                Resource: !Sub 'arn:aws:s3:::${Prefix}/*'
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource: !Sub 'arn:aws:s3:::${Prefix}'
  AddSetupUserToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    DependsOn: SetupUserGroup
    Properties:
      GroupName: !Sub '${Prefix}-setupUserGroup'
      Users:
        - !Ref SetupUser
  SetupUserAccessKeys:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName:
        Ref: SetupUser
  SetupUserPolicy:
    Type: 'AWS::IAM::Policy'
    DependsOn:
      - SetupUserGroup
      - SetupUser
    Properties:
      PolicyName: !Sub '${Prefix}-SetupUserPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
              - secretsmanager:* # test
            Resource: '*'
      Groups:
        - !Sub '${Prefix}-setupUserGroup'

  #
  # ECS Fargate roles
  #
  EcsContainerRole:
    Type: AWS::IAM::Role
    DependsOn: SetupUser
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service:
              - "lambda.amazonaws.com"
              - "ecs-tasks.amazonaws.com"
            AWS:
              - !GetAtt SetupUser.Arn
          Action:
            - sts:AssumeRole
      Path: "/"

  # # @todo - restrict
  EcsContainerExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: SetupUser
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        # - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        # - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSCloudMapFullAccess # for Route 53 routing and service discovery?
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        #- arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess
        #- arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess #important for the creation of the log group
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service:
              - "lambda.amazonaws.com"
              - "ecs-tasks.amazonaws.com"
            AWS:
              - !GetAtt SetupUser.Arn
          Action:
            - sts:AssumeRole
      Policies:
        - PolicyName: PimcoreDeployerSecretsManagerReadAccess # read access to secrets of the app's namespace
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'secretsmanager:DescribeSecret'
                  - 'secretsmanager:GetSecretValue'
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Prefix}*'
      Path: "/"

Outputs:
  SetupUserAccessKey:
    Description: "Setup User Access Key"
    Value: !Ref SetupUserAccessKeys
  SetupUserAccessToken:
    Description: "Setup User Access token"
    Value: !GetAtt SetupUserAccessKeys.SecretAccessKey
  SetupUserArn:
    Description: "Setup User ARN"
    Value: !GetAtt SetupUser.Arn
  EcsContainerTaskExecutionRole:
    Description: "ECS Fargate Container Task Execution role (will be used on container startup)."
    Value: !GetAtt EcsContainerExecutionRole.Arn
  EcsContainerTaskRole:
    Description: "ECS Fargate Container Task role (will be used for the container application)."
    Value: !GetAtt EcsContainerRole.Arn